# Site settings
title: Greg Baute
email: gregbaute@gmail.com
baseurl: https://gbaute.github.io #"" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Crop improvement and genomics

# Social icons
#facebook: username
linkedin: greg-baute-a2b012115
github: gbaute
twitter_username: gregbaute
google_scholar: m0LJafcAAAAJ
#deviantart: username
#codepen: username

footer: Â© Taken theme

# Build settings
markdown: kramdown
